files = [
    "./resources/bonzai.tif",
    "./resources/cameraman.tif",
    "./resources/diagonal_left_100x100.tif",
    "./resources/grayscale_test_1.png",
    "./resources/house.tif",
    "./resources/jetplane.tif",
    "./resources/lake.tif",
    # "./resources/lena_color_256.tif",
    # "./resources/lena_color_512.tif",
    "./resources/lena_gray_256.tif",
    # "./resources/lena_gray_512.tif",
    "./resources/link.png",
    "./resources/livingroom.tif",
    # "./resources/mandril_color.tif",
    "./resources/mandril_gray.tif",
    "./resources/multi_grayscale_1_100x100.tif",
    # "./resources/peppers_color.tif",
    "./resources/peppers_gray.tif",
    "./resources/pirate.tif",
    "./resources/plus_100x100.tif",
    "./resources/walkbridge.tif",
    "./resources/woman_blonde.tif",
    "./resources/woman_darkhair.tif"
]